name: Fetch & build

on:
  workflow_dispatch:

jobs:
  build:
    name: Fetch & build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'
      - run: |
          npm install
          npm run google
      - name: Commit files
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest build: ${timestamp}" || exit 0
          git push
      - name: Trigger Netlify build
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/6169084111a3855de5c05ccb
