name: Fetch & build

on:
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install deps
      - run: npm install
      - name: Fetch Google sheet data
      - run: npm run google
      - name: Build static site
      - run: npm run build
      - name: Commit & push
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest build: ${timestamp}" || exit 0
          git push
